version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
  - package-ecosystem: npm
    directory: "/core/publish-key"
    schedule:
      interval: "weekly"
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
