AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "Digital Identity IPV CRI Core Infrastructure"

Parameters:
  Environment:
    Description: "The environment type"
    Type: "String"
    AllowedValues:
      - "dev"
      - "build"
      - "staging"
      - "integration"
      - "production"
    ConstraintDescription: must be dev, build, staging, integration or production


Resources:
  CommonCRIWAFAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:apigateway:eu-west-2::/restapis/"
            - Fn::ImportValue: "kbv-cri-api-v1-KBVApiGatewayId"
            - !Sub "/stages/${Environment}"
      WebACLArn:
        Fn::ImportValue: "CriWebAclARN"

