name: Check PR

on: pull_request
permissions: {}

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    concurrency:
      group: pre-commit-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Pull repository
        uses: actions/checkout@v6

      - name: Set up node
        uses: actions/setup-node@v6
        with:
          cache-dependency-path: core/publish-key/package-lock.json
          node-version-file: core/publish-key/.nvmrc
          cache: npm

      - name: Install npm dependencies
        working-directory: core/publish-key
        run: npm ci

      - name: Run pre-commit
        uses: govuk-one-login/github-actions/code-quality/run-pre-commit@350c58b28e56f0fd67c4a8d8c8cd4fdc6355bdf3
        with:
          pull-repository: false
          all-files: true

  run-unit-tests-publish-key-fn:
    name: Run unit tests (publish key function)
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: govuk-one-login/github-actions/node/run-script@cfdec064a0b8d033516eba4999ed35578b262f0a
        with:
          working-directory: core/publish-key
          node-version-file: core/publish-key/.nvmrc
          script: npm run test:coverage
